name = "gofio-bot"
main = "src/index.ts"
compatibility_date = "2024-05-11"

# Declare a Cloudflare Worker KV namespace
# See https://developers.cloudflare.com/workers/wrangler/workers-kv/
# and https://developers.cloudflare.com/workers/runtime-apis/kv/
#
# [[kv_namespaces]]
# binding = "<BINDING_NAME>"
# id = "<KV_NAMESPACE_ID>"

# Set up cron triggers
# See https://developers.cloudflare.com/workers/examples/cron-trigger/
#
[[d1_databases]]
binding = "DB"
database_name = "gofio-bot-d1"
database_id = "756e85b6-8845-45a0-81a6-be53e40d4986"


[triggers]
crons = ["0 10 * * 1,3,5"]
# crons = ["* * * * *"]
